# Generated by Django 5.0.6 on 2025-10-29 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique file identifier (UUID)', primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file', models.FileField(help_text='Encrypted file data on disk', upload_to='encrypted_files/')),
                ('file_size', models.BigIntegerField(help_text='Original file size in bytes (before encryption)')),
                ('nonce', models.CharField(help_text='AES-GCM nonce (base64 encoded)', max_length=64)),
                ('tag', models.CharField(help_text='AES-GCM authentication tag (base64 encoded)', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='Group this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='groups.filegroup')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encrypted File',
                'verbose_name_plural': 'Encrypted Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_aes_key', models.TextField(help_text="AES key encrypted with user's RSA public key (base64)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(help_text='The encrypted file', on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to='files.encryptedfile')),
                ('user', models.ForeignKey(help_text='User who can decrypt this file', on_delete=django.db.models.deletion.CASCADE, related_name='file_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Encryption Key',
                'verbose_name_plural': 'File Encryption Keys',
                'unique_together': {('file', 'user')},
            },
        ),
    ]
