# Generated by Django 5.0.6 on 2025-10-29 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this group', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this group is for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Users who can access files in this group', related_name='file_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Group',
                'verbose_name_plural': 'File Groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
